### ISSUE TITLE
support to parse .scn files with multiple languages?

### ISSUE THREAD

**Issue by xenei** [HoodedTissue/KiriKiriSCNJSONParser#1]
Hey, I want saw your scripts to parse .scn files and this is honestly really good, but I'm facing problem with parsing .scn files that have multiple languages like the recent .scn files from Hello Lady! 
![sad](https://user-images.githubusercontent.com/91423244/151784087-0749f308-160a-478c-908f-414fba696781.PNG)
See rather than having one there's total 5 and for that reason it can't parse. I am also no good with programming language so I can't modify the script myself to make it parse the english text only. Therefore I was wondering if you make a script>? or something...
I'll attach the following files if you need to check.
[KiriKiriSCNJSONParser.zip](https://github.com/HoodedTissue/KiriKiriSCNJSONParser/files/7970277/KiriKiriSCNJSONParser.zip)

**Comment by HoodedTissue** [comment]
Hi.
I'm suprised that someone is actually looking at my code besides me. I mainly only made this tool for a [personal project](https://vndb.org/v19441) and to practice coding though I'd love to help. Only issue is that I'm still learning to program so it's not guaranteed that I'll be able to make a script for Hello Lady!'s scn files and I also don't have very much free time these days so if I were to help you it would take a very long time. It's probably best that you use something better such as [SCNEditorGUI](https://github.com/marcussacana/KrKrZSceneManager) for now instead of waiting for me to make something that may not even work.

**Comment by xenei** [comment]
Oh hey, thanks for the response, I appreciate it. I will go with SCN-Editor then.
